namespace Spdx3.Model.Core.Enums;

/// <summary>
///     The type of an external reference.
///     See https://spdx.github.io/spdx-spec/v3.0.1/model/Core/Vocabularies/ExternalRefType/
/// </summary>
public enum ExternalRefType
{
    altDownloadLocation,
    altWebPage,
    binaryArtifact,
    bower,
    buildMeta,
    buildSystem,
    certificationReport,
    chat,
    componentAnalysisReport,
    cwe,
    documentation,
    dynamicAnalysisReport,
    eolNotice,
    exportControlAssessment,
    funding,
    issueTracker,
    license,
    mailingList,
    mavenCentral,
    metrics,
    npm,
    nuget,
    other,
    privacyAssessment,
    productMetadata,
    purchaseOrder,
    qualityAssessmentReport,
    releaseHistory,
    releaseNotes,
    riskAssessment,
    runtimeAnalysisReport,
    secureSoftwareAttestation,
    securityAdversaryModel,
    securityAdvisory,
    securityFix,
    securityOther,
    securityPenTestReport,
    securityPolicy,
    securityThreatModel,
    socialMedia,
    sourceArtifact,
    staticAnalysisReport,
    support,
    vcs,
    vulnerabilityDisclosureReport,
    vulnerabilityExploitabilityAssessment
}