name: Demos

on:
  push:
    branches:
      - issue-33
    paths:
      - demos.yml

jobs:
  build:
    name: Demos
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore local tools
        run: dotnet tool restore
        
      - name: Create Source SBOM
        run: dotnet run --project ProduceSourceSbom --verbose=true -l=false --projectPath=./ProduceBuildSbom/ProduceBuildSbom.csproj --outputDir=. --fileName spdx3.sbom.source.json 

      - name: Create Build SBOM
        run: dotnet run --project ProduceBuildSbom --verbose=true -l=false --sourceSbomPath=./spdx3.sbom.source.json --outputDir=. --fileName spdx3.sbom.build.json
